type ChatRoom {
    id: String!
    chatRoomName: String!
    userIds: [String!]!
    chatRoomType: ChatRoomType!
    unreadMessageCount: Int!
    latestMessage: Message!
    isExited: Boolean
}

type ChatMessage {
    id: String
    senderId: String
    deletedForEveryone: Boolean!
    name: String
    content: String!
    timestamp: String!
    status: MessageStatus
}

type NotificationMessage {
    id: String
    content: String!
    timestamp: String!
}

union Message = ChatMessage | NotificationMessage

enum MessageStatus {
    DELIVERED
    READ
    PENDING
    FAILED
    DELETED
}

enum ChatRoomType {
    DIRECT
    GROUP
    SELF
}

type User {
    id: String!
    username: String!
}

interface IOnlineUsersDTO {
    lastSeenTimestamp: String
}

type DirectChatOnlineUsersDTO implements IOnlineUsersDTO {
    lastSeenTimestamp: String
}

type SelfChatOnlineUsersDTO implements IOnlineUsersDTO {
    lastSeenTimestamp: String
}

type GroupChatOnlineUsersDTO implements IOnlineUsersDTO {
    onlineUsers: [String]!
    lastSeenTimestamp: String
}

type ChatRoomData {
    messages: [Message!]!
    onlineUsersDTO: IOnlineUsersDTO
}

type Query {
    getChatRoomsOfUser: [ChatRoom!]!
    getChatRoomData(chatRoomId: String!): ChatRoomData!
}

