spring.profiles.active=local

#spring.data.mongodb.uri=
#server.http2.enabled=true

# Redis Set Up
#spring.redis.url=

server.port=8080


# Kafka broker addresses
spring.kafka.bootstrap-servers=localhost:9092

# cd ../../kafka/bin/windows && zookeeper-server-start.bat ../../config/zookeeper.properties
# cd ../../kafka/bin/windows && kafka-server-start.bat ../../config/server.properties

#graphql.servlet.mapping=/graphql
#graphql.servlet.enabled=true
#graphql.servlet.corsEnabled=true
#graphql.servlet.exception-handlers-enabled=true
#graphql.tools.schema-location=classpath:graphql/chat.graphqls

#Secret Key
converse.jwt.key=eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcxOTI5NTcxMiwiaWF0IjoxNzE5Mjk1NzEyfQOUVbN64TPx5zoiVyFbXxbGxhhUY6hqMpwvSgKtkOI8Q
converse.jwt.expiration=600000

messageValidTimeDiffForDeletingForEveryone=60000

